name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

  dockerize:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t my-todo-app .
          docker tag my-todo-app:latest ${{ secrets.DOCKER_USERNAME }}/my-todo-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-todo-app:latest

      - name: Log out from Docker Hub
        run: docker logout

  deploy:
    needs: [dockerize]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH for EC2
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-todo-app:latest
          docker stop my-todo-app || true
          docker rm my-todo-app || true
          docker rmi $(docker images -f "dangling=true" -q) || true
          docker run -d --name my-todo-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-todo-app:latest
          docker system prune -af || true
          EOF

      - name: Cleanup local SSH key
        run: rm ec2_key.pem